### ISSUE TITLE
Figure out why logging is done over stdout/err instead of file

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/ad-ldap-connector-rpm#1]
According to the docs, logging happens in /var/log/auth0-adldap.log (https://auth0.com/docs/connector/troubleshooting)

**Comment by gcoxmoz** [comment]
I've reported the lack of `/var/log/auth0-adldap.log`, and the logging going to stdout/journald hasn't really been that big of an issue.  I don't think this is going to be pursued and so I'm closing this as a noop until proven otherwise.
